package com.translation.dao;

import com.translation.bean.Comment;
import com.translation.bean.CommentExample;
import java.util.List;

public interface CommentDAO {

	
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int countByExample(CommentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer comid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	void insert(Comment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	void insertSelective(Comment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	List selectByExample(CommentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	Comment selectByPrimaryKey(Integer comid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByExampleSelective(Comment record, CommentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByExample(Comment record, CommentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByPrimaryKey(Comment record);

	/**
	 * @author 浩然
	 * 分页获取Comment
	 * @param startCount
	 * @param maxCount
	 * @param commentExample
	 * @return
	 */
	List selectByPage(int startCount,int maxCount,CommentExample commentExample);
}