package com.translation.dao;

import com.translation.bean.Friend;
import com.translation.bean.FriendExample;
import java.util.List;

public interface FriendDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int countByExample(FriendExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int deleteByExample(FriendExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int deleteByPrimaryKey(Integer friendid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	void insert(Friend record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	void insertSelective(Friend record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	List selectByExample(FriendExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	Friend selectByPrimaryKey(Integer friendid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int updateByExampleSelective(Friend record, FriendExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int updateByExample(Friend record, FriendExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int updateByPrimaryKeySelective(Friend record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	int updateByPrimaryKey(Friend record);
}