package com.translation.dao;

import com.translation.bean.Invite;
import com.translation.bean.InviteExample;
import java.util.List;

public interface InviteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int countByExample(InviteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int deleteByExample(InviteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int deleteByPrimaryKey(Integer inviteid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	void insert(Invite record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	void insertSelective(Invite record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	List selectByExample(InviteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	Invite selectByPrimaryKey(Integer inviteid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int updateByExampleSelective(Invite record, InviteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int updateByExample(Invite record, InviteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int updateByPrimaryKeySelective(Invite record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Mon Aug 24 18:07:53 CST 2015
	 */
	int updateByPrimaryKey(Invite record);
}