package com.translation.dao;

import com.translation.bean.User;
import com.translation.bean.UserExample;

import java.util.List;


public interface UserDAO {

	
	
	/**
	 * @author 浩然
	 * @param record
	 * @return
	 */
	public Integer insertSelectiveRet(User record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	void insert(User record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	void insertSelective(User record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	List selectByExample(UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	User selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int updateByExampleSelective(User record, UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int updateByExample(User record, UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	int updateByPrimaryKey(User record);
}