package com.translation.dao;

import com.translation.bean.Want;
import com.translation.bean.WantExample;

import java.util.List;

public interface WantDAO {

	
	
	
	public List selectByGroup(WantExample example,int skipResults,int maxResults);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int countByExample(WantExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int deleteByExample(WantExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer wantid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	void insert(Want record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	void insertSelective(Want record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	List selectByExample(WantExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	Want selectByPrimaryKey(Integer wantid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByExampleSelective(Want record, WantExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByExample(Want record, WantExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByPrimaryKeySelective(Want record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	int updateByPrimaryKey(Want record);
	
	/**
	 * @author 浩然
	 * @param skipCount
	 * @param maxCount
	 * @param example
	 * @return
	 */
	public List<Want> selectByPage(int skipCount,int maxCount,WantExample example);
}