package com.translation.bean;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.comid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer comid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.docid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer docid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.userid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.creattime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Date creattime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.edittime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Date edittime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.liketimes
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer liketimes;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.isaccept
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private String isaccept;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.content
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private String content;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.delflag
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private String delflag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.isnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private String isnew;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column comment.acceptnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private String acceptnew;

	
	
	
	private User user;
	private int likeTime;
	private String canDel;
	
	
	private Document document;
	
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	
	
	public int getLikeTime() {
		return likeTime;
	}

	public void setLikeTime(int likeTime) {
		this.likeTime = likeTime;
	}

	public Document getDocument() {
		return document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	
	
	public String getCanDel() {
		return canDel;
	}

	public void setCanDel(String canDel) {
		this.canDel = canDel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.comid
	 * @return  the value of comment.comid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */


	public Integer getComid() {
		return comid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.comid
	 * @param comid  the value for comment.comid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setComid(Integer comid) {
		this.comid = comid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.docid
	 * @return  the value of comment.docid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Integer getDocid() {
		return docid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.docid
	 * @param docid  the value for comment.docid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setDocid(Integer docid) {
		this.docid = docid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.userid
	 * @return  the value of comment.userid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.userid
	 * @param userid  the value for comment.userid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.creattime
	 * @return  the value of comment.creattime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.creattime
	 * @param creattime  the value for comment.creattime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.edittime
	 * @return  the value of comment.edittime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Date getEdittime() {
		return edittime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.edittime
	 * @param edittime  the value for comment.edittime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setEdittime(Date edittime) {
		this.edittime = edittime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.liketimes
	 * @return  the value of comment.liketimes
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Integer getLiketimes() {
		return liketimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.liketimes
	 * @param liketimes  the value for comment.liketimes
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setLiketimes(Integer liketimes) {
		this.liketimes = liketimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.isaccept
	 * @return  the value of comment.isaccept
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public String getIsaccept() {
		return isaccept;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.isaccept
	 * @param isaccept  the value for comment.isaccept
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setIsaccept(String isaccept) {
		this.isaccept = isaccept;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.content
	 * @return  the value of comment.content
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.content
	 * @param content  the value for comment.content
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.delflag
	 * @return  the value of comment.delflag
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.delflag
	 * @param delflag  the value for comment.delflag
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.isnew
	 * @return  the value of comment.isnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public String getIsnew() {
		return isnew;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.isnew
	 * @param isnew  the value for comment.isnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setIsnew(String isnew) {
		this.isnew = isnew;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column comment.acceptnew
	 * @return  the value of comment.acceptnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public String getAcceptnew() {
		return acceptnew;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column comment.acceptnew
	 * @param acceptnew  the value for comment.acceptnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setAcceptnew(String acceptnew) {
		this.acceptnew = acceptnew;
	}
}