package com.translation.bean;

import java.util.Date;

public class Document {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.docid
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private Integer docid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.userid
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.title
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.content
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.creattime
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private Date creattime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.edittime
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private Date edittime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.point
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column document.delflag
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private String delflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.docid
     *
     * @return the value of document.docid
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.docid
     *
     * @param docid the value for document.docid
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.userid
     *
     * @return the value of document.userid
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.userid
     *
     * @param userid the value for document.userid
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.title
     *
     * @return the value of document.title
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.title
     *
     * @param title the value for document.title
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.content
     *
     * @return the value of document.content
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.content
     *
     * @param content the value for document.content
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.creattime
     *
     * @return the value of document.creattime
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.creattime
     *
     * @param creattime the value for document.creattime
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.edittime
     *
     * @return the value of document.edittime
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public Date getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.edittime
     *
     * @param edittime the value for document.edittime
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setEdittime(Date edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.point
     *
     * @return the value of document.point
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.point
     *
     * @param point the value for document.point
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column document.delflag
     *
     * @return the value of document.delflag
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column document.delflag
     *
     * @param delflag the value for document.delflag
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag;
    }
}