package com.translation.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FriendExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public FriendExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	protected FriendExample(FriendExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table friend
	 * @ibatorgenerated  Thu Apr 23 16:51:31 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andFriendidIsNull() {
			addCriterion("friendid is null");
			return this;
		}

		public Criteria andFriendidIsNotNull() {
			addCriterion("friendid is not null");
			return this;
		}

		public Criteria andFriendidEqualTo(Integer value) {
			addCriterion("friendid =", value, "friendid");
			return this;
		}

		public Criteria andFriendidNotEqualTo(Integer value) {
			addCriterion("friendid <>", value, "friendid");
			return this;
		}

		public Criteria andFriendidGreaterThan(Integer value) {
			addCriterion("friendid >", value, "friendid");
			return this;
		}

		public Criteria andFriendidGreaterThanOrEqualTo(Integer value) {
			addCriterion("friendid >=", value, "friendid");
			return this;
		}

		public Criteria andFriendidLessThan(Integer value) {
			addCriterion("friendid <", value, "friendid");
			return this;
		}

		public Criteria andFriendidLessThanOrEqualTo(Integer value) {
			addCriterion("friendid <=", value, "friendid");
			return this;
		}

		public Criteria andFriendidIn(List values) {
			addCriterion("friendid in", values, "friendid");
			return this;
		}

		public Criteria andFriendidNotIn(List values) {
			addCriterion("friendid not in", values, "friendid");
			return this;
		}

		public Criteria andFriendidBetween(Integer value1, Integer value2) {
			addCriterion("friendid between", value1, value2, "friendid");
			return this;
		}

		public Criteria andFriendidNotBetween(Integer value1, Integer value2) {
			addCriterion("friendid not between", value1, value2, "friendid");
			return this;
		}

		public Criteria andPrimidIsNull() {
			addCriterion("primid is null");
			return this;
		}

		public Criteria andPrimidIsNotNull() {
			addCriterion("primid is not null");
			return this;
		}

		public Criteria andPrimidEqualTo(Integer value) {
			addCriterion("primid =", value, "primid");
			return this;
		}

		public Criteria andPrimidNotEqualTo(Integer value) {
			addCriterion("primid <>", value, "primid");
			return this;
		}

		public Criteria andPrimidGreaterThan(Integer value) {
			addCriterion("primid >", value, "primid");
			return this;
		}

		public Criteria andPrimidGreaterThanOrEqualTo(Integer value) {
			addCriterion("primid >=", value, "primid");
			return this;
		}

		public Criteria andPrimidLessThan(Integer value) {
			addCriterion("primid <", value, "primid");
			return this;
		}

		public Criteria andPrimidLessThanOrEqualTo(Integer value) {
			addCriterion("primid <=", value, "primid");
			return this;
		}

		public Criteria andPrimidIn(List values) {
			addCriterion("primid in", values, "primid");
			return this;
		}

		public Criteria andPrimidNotIn(List values) {
			addCriterion("primid not in", values, "primid");
			return this;
		}

		public Criteria andPrimidBetween(Integer value1, Integer value2) {
			addCriterion("primid between", value1, value2, "primid");
			return this;
		}

		public Criteria andPrimidNotBetween(Integer value1, Integer value2) {
			addCriterion("primid not between", value1, value2, "primid");
			return this;
		}

		public Criteria andGuestidIsNull() {
			addCriterion("guestid is null");
			return this;
		}

		public Criteria andGuestidIsNotNull() {
			addCriterion("guestid is not null");
			return this;
		}

		public Criteria andGuestidEqualTo(Integer value) {
			addCriterion("guestid =", value, "guestid");
			return this;
		}

		public Criteria andGuestidNotEqualTo(Integer value) {
			addCriterion("guestid <>", value, "guestid");
			return this;
		}

		public Criteria andGuestidGreaterThan(Integer value) {
			addCriterion("guestid >", value, "guestid");
			return this;
		}

		public Criteria andGuestidGreaterThanOrEqualTo(Integer value) {
			addCriterion("guestid >=", value, "guestid");
			return this;
		}

		public Criteria andGuestidLessThan(Integer value) {
			addCriterion("guestid <", value, "guestid");
			return this;
		}

		public Criteria andGuestidLessThanOrEqualTo(Integer value) {
			addCriterion("guestid <=", value, "guestid");
			return this;
		}

		public Criteria andGuestidIn(List values) {
			addCriterion("guestid in", values, "guestid");
			return this;
		}

		public Criteria andGuestidNotIn(List values) {
			addCriterion("guestid not in", values, "guestid");
			return this;
		}

		public Criteria andGuestidBetween(Integer value1, Integer value2) {
			addCriterion("guestid between", value1, value2, "guestid");
			return this;
		}

		public Criteria andGuestidNotBetween(Integer value1, Integer value2) {
			addCriterion("guestid not between", value1, value2, "guestid");
			return this;
		}

		public Criteria andIsnewIsNull() {
			addCriterion("isnew is null");
			return this;
		}

		public Criteria andIsnewIsNotNull() {
			addCriterion("isnew is not null");
			return this;
		}

		public Criteria andIsnewEqualTo(String value) {
			addCriterion("isnew =", value, "isnew");
			return this;
		}

		public Criteria andIsnewNotEqualTo(String value) {
			addCriterion("isnew <>", value, "isnew");
			return this;
		}

		public Criteria andIsnewGreaterThan(String value) {
			addCriterion("isnew >", value, "isnew");
			return this;
		}

		public Criteria andIsnewGreaterThanOrEqualTo(String value) {
			addCriterion("isnew >=", value, "isnew");
			return this;
		}

		public Criteria andIsnewLessThan(String value) {
			addCriterion("isnew <", value, "isnew");
			return this;
		}

		public Criteria andIsnewLessThanOrEqualTo(String value) {
			addCriterion("isnew <=", value, "isnew");
			return this;
		}

		public Criteria andIsnewLike(String value) {
			addCriterion("isnew like", value, "isnew");
			return this;
		}

		public Criteria andIsnewNotLike(String value) {
			addCriterion("isnew not like", value, "isnew");
			return this;
		}

		public Criteria andIsnewIn(List values) {
			addCriterion("isnew in", values, "isnew");
			return this;
		}

		public Criteria andIsnewNotIn(List values) {
			addCriterion("isnew not in", values, "isnew");
			return this;
		}

		public Criteria andIsnewBetween(String value1, String value2) {
			addCriterion("isnew between", value1, value2, "isnew");
			return this;
		}

		public Criteria andIsnewNotBetween(String value1, String value2) {
			addCriterion("isnew not between", value1, value2, "isnew");
			return this;
		}
	}
}