package com.translation.bean;

import java.util.Date;

public class Love {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column love.likeid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    private Integer likeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column love.userid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column love.commid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    private Integer commid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column love.isnew
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    private String isnew;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column love.creattime
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    private Date creattime;

    
    private User user;
    private Comment comment;
    
    
    public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Comment getComment() {
		return comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column love.likeid
     *
     * @return the value of love.likeid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public Integer getLikeid() {
        return likeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column love.likeid
     *
     * @param likeid the value for love.likeid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public void setLikeid(Integer likeid) {
        this.likeid = likeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column love.userid
     *
     * @return the value of love.userid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column love.userid
     *
     * @param userid the value for love.userid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column love.commid
     *
     * @return the value of love.commid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public Integer getCommid() {
        return commid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column love.commid
     *
     * @param commid the value for love.commid
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public void setCommid(Integer commid) {
        this.commid = commid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column love.isnew
     *
     * @return the value of love.isnew
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public String getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column love.isnew
     *
     * @param isnew the value for love.isnew
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column love.creattime
     *
     * @return the value of love.creattime
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column love.creattime
     *
     * @param creattime the value for love.creattime
     *
     * @ibatorgenerated Thu Apr 16 22:47:44 CST 2015
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }
}