package com.translation.bean;

public class User {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.userId
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.userName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.password
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.email
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.web
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String web;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.firstName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String firstname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.lastName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String lastname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.delFlag
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private String delflag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.point
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private Integer point;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.userId
	 * @return  the value of user.userId
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.userId
	 * @param userid  the value for user.userId
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.userName
	 * @return  the value of user.userName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.userName
	 * @param username  the value for user.userName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.web
	 * @return  the value of user.web
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getWeb() {
		return web;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.web
	 * @param web  the value for user.web
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setWeb(String web) {
		this.web = web;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.firstName
	 * @return  the value of user.firstName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.firstName
	 * @param firstname  the value for user.firstName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.lastName
	 * @return  the value of user.lastName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.lastName
	 * @param lastname  the value for user.lastName
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.delFlag
	 * @return  the value of user.delFlag
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.delFlag
	 * @param delflag  the value for user.delFlag
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.point
	 * @return  the value of user.point
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public Integer getPoint() {
		return point;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.point
	 * @param point  the value for user.point
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}
}