package com.translation.bean;

import java.util.Date;

public class Want {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column want.wantid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer wantid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column want.userid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column want.docid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Integer docid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column want.isnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private String isnew;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column want.creattime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private Date creattime;

	
	private Document document;
	private User user;
	
	
	
	
	
	public Document getDocument() {
		return document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column want.wantid
	 * @return  the value of want.wantid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Integer getWantid() {
		return wantid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column want.wantid
	 * @param wantid  the value for want.wantid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setWantid(Integer wantid) {
		this.wantid = wantid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column want.userid
	 * @return  the value of want.userid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column want.userid
	 * @param userid  the value for want.userid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column want.docid
	 * @return  the value of want.docid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Integer getDocid() {
		return docid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column want.docid
	 * @param docid  the value for want.docid
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setDocid(Integer docid) {
		this.docid = docid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column want.isnew
	 * @return  the value of want.isnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public String getIsnew() {
		return isnew;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column want.isnew
	 * @param isnew  the value for want.isnew
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setIsnew(String isnew) {
		this.isnew = isnew;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column want.creattime
	 * @return  the value of want.creattime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column want.creattime
	 * @param creattime  the value for want.creattime
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}
}