package com.translation.dao.impl;

import com.translation.bean.Comment;
import com.translation.bean.CommentExample;
import com.translation.dao.CommentDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CommentDAOImpl extends SqlMapClientDaoSupport implements CommentDAO {

	
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public CommentDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int countByExample(CommentExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"comment.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int deleteByExample(CommentExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"comment.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int deleteByPrimaryKey(Integer comid) {
		Comment key = new Comment();
		key.setComid(comid);
		int rows = getSqlMapClientTemplate().delete(
				"comment.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void insert(Comment record) {
		getSqlMapClientTemplate().insert("comment.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void insertSelective(Comment record) {
		getSqlMapClientTemplate().insert(
				"comment.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public List selectByExample(CommentExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"comment.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Comment selectByPrimaryKey(Integer comid) {
		Comment key = new Comment();
		key.setComid(comid);
		Comment record = (Comment) getSqlMapClientTemplate().queryForObject(
				"comment.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByExampleSelective(Comment record, CommentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"comment.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByExample(Comment record, CommentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"comment.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByPrimaryKeySelective(Comment record) {
		int rows = getSqlMapClientTemplate().update(
				"comment.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByPrimaryKey(Comment record) {
		int rows = getSqlMapClientTemplate().update(
				"comment.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table comment
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private static class UpdateByExampleParms extends CommentExample {
		private Object record;

		public UpdateByExampleParms(Object record, CommentExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	/**
	 * @author 浩然
	 * 
	 * 分页获取Comment
	 */
	public List selectByPage(int startCount, int maxCount,
			CommentExample commentExample) {
		return getSqlMapClientTemplate().queryForList("comment.ibatorgenerated_selectByExample", commentExample, startCount, maxCount);
	}


}