package com.translation.dao.impl;

import com.translation.bean.Document;
import com.translation.bean.DocumentExample;
import com.translation.dao.DocumentDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DocumentDAOImpl extends SqlMapClientDaoSupport implements DocumentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public DocumentDAOImpl() {
        super();
    }
    
    
    /**
     * @author 浩然
     * 分页查询
     * @param startCount
     * @param maxCount
     * @param example
     * @return
     */
    public List selectByPage(int startCount,int maxCount,DocumentExample example){
    	List list = getSqlMapClientTemplate().queryForList("document.ibatorgenerated_selectByExample", example,startCount, maxCount);
    	return list;
    }
    
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int countByExample(DocumentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("document.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int deleteByExample(DocumentExample example) {
        int rows = getSqlMapClientTemplate().delete("document.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int deleteByPrimaryKey(Integer docid) {
        Document key = new Document();
        key.setDocid(docid);
        int rows = getSqlMapClientTemplate().delete("document.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void insert(Document record) {
        getSqlMapClientTemplate().insert("document.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public void insertSelective(Document record) {
        getSqlMapClientTemplate().insert("document.ibatorgenerated_insertSelective", record);
    }
    
    
    
    public Integer insertSelectiveRet(Document record) {
        return (Integer)getSqlMapClientTemplate().insert("document.ibatorgenerated_insertSelectiveRet", record);
    }
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public List selectByExample(DocumentExample example) {
        List list = getSqlMapClientTemplate().queryForList("document.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public Document selectByPrimaryKey(Integer docid) {
        Document key = new Document();
        key.setDocid(docid);
        Document record = (Document) getSqlMapClientTemplate().queryForObject("document.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int updateByExampleSelective(Document record, DocumentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("document.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int updateByExample(Document record, DocumentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("document.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int updateByPrimaryKeySelective(Document record) {
        int rows = getSqlMapClientTemplate().update("document.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    public int updateByPrimaryKey(Document record) {
        int rows = getSqlMapClientTemplate().update("document.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table document
     *
     * @ibatorgenerated Thu Apr 09 21:28:14 CST 2015
     */
    private static class UpdateByExampleParms extends DocumentExample {
        private Object record;

        public UpdateByExampleParms(Object record, DocumentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}