package com.translation.dao.impl;

import com.translation.bean.Invite;
import com.translation.bean.InviteExample;
import com.translation.dao.InviteDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class InviteDAOImpl extends SqlMapClientDaoSupport implements InviteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public InviteDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int countByExample(InviteExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"invite.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int deleteByExample(InviteExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"invite.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int deleteByPrimaryKey(Integer inviteid) {
		Invite key = new Invite();
		key.setInviteid(inviteid);
		int rows = getSqlMapClientTemplate().delete(
				"invite.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public void insert(Invite record) {
		getSqlMapClientTemplate().insert("invite.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public void insertSelective(Invite record) {
		getSqlMapClientTemplate().insert(
				"invite.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public List selectByExample(InviteExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"invite.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public Invite selectByPrimaryKey(Integer inviteid) {
		Invite key = new Invite();
		key.setInviteid(inviteid);
		Invite record = (Invite) getSqlMapClientTemplate().queryForObject(
				"invite.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int updateByExampleSelective(Invite record, InviteExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"invite.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int updateByExample(Invite record, InviteExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"invite.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int updateByPrimaryKeySelective(Invite record) {
		int rows = getSqlMapClientTemplate().update(
				"invite.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	public int updateByPrimaryKey(Invite record) {
		int rows = getSqlMapClientTemplate().update(
				"invite.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table invite
	 * @ibatorgenerated  Thu Apr 23 16:51:42 CST 2015
	 */
	private static class UpdateByExampleParms extends InviteExample {
		private Object record;

		public UpdateByExampleParms(Object record, InviteExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}