package com.translation.dao.impl;

import com.translation.bean.User;
import com.translation.bean.UserExample;
import com.translation.dao.UserDAO;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public UserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int countByExample(UserExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"user.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int deleteByExample(UserExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"user.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int deleteByPrimaryKey(Integer userid) {
		User key = new User();
		key.setUserid(userid);
		int rows = getSqlMapClientTemplate().delete(
				"user.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void insert(User record) {
		getSqlMapClientTemplate().insert("user.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public void insertSelective(User record) {
		getSqlMapClientTemplate().insert(
				"user.ibatorgenerated_insertSelective", record);
	}

	/**
	 * @author 浩然
	 * @param record
	 * @return
	 */
	public Integer insertSelectiveRet(User record) {
		return (Integer)getSqlMapClientTemplate().insert(
				"user.ibatorgenerated_insertSelectiveRet", record);
	}
	
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public List selectByExample(UserExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"user.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public User selectByPrimaryKey(Integer userid) {
		User key = new User();
		key.setUserid(userid);
		User record = (User) getSqlMapClientTemplate().queryForObject(
				"user.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int updateByExampleSelective(User record, UserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int updateByExample(User record, UserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int updateByPrimaryKeySelective(User record) {
		int rows = getSqlMapClientTemplate().update(
				"user.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	public int updateByPrimaryKey(User record) {
		int rows = getSqlMapClientTemplate().update(
				"user.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table user
	 * @ibatorgenerated  Thu Apr 09 21:28:14 CST 2015
	 */
	private static class UpdateByExampleParms extends UserExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}