package com.translation.dao.impl;

import com.translation.bean.Want;
import com.translation.bean.WantExample;
import com.translation.dao.WantDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WantDAOImpl extends SqlMapClientDaoSupport implements WantDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public WantDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int countByExample(WantExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"want.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int deleteByExample(WantExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"want.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int deleteByPrimaryKey(Integer wantid) {
		Want key = new Want();
		key.setWantid(wantid);
		int rows = getSqlMapClientTemplate().delete(
				"want.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void insert(Want record) {
		getSqlMapClientTemplate().insert("want.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public void insertSelective(Want record) {
		getSqlMapClientTemplate().insert(
				"want.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public List selectByExample(WantExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"want.ibatorgenerated_selectByExample", example);
		return list;
	}

	
	/**
	 * 分组查询
	 * @author 浩然
	 * @param dcoid
	 * @param example
	 * @param skipResults
	 * @param maxResults
	 * @return
	 */
	public List selectByGroup(WantExample example,int skipResults,int maxResults){
		List list = getSqlMapClientTemplate().queryForList("want.ibatorgenerated_selectByGroup", example, skipResults, maxResults);
		return list;
	}
	
	
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public Want selectByPrimaryKey(Integer wantid) {
		Want key = new Want();
		key.setWantid(wantid);
		Want record = (Want) getSqlMapClientTemplate().queryForObject(
				"want.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByExampleSelective(Want record, WantExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"want.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByExample(Want record, WantExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"want.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByPrimaryKeySelective(Want record) {
		int rows = getSqlMapClientTemplate().update(
				"want.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	public int updateByPrimaryKey(Want record) {
		int rows = getSqlMapClientTemplate().update(
				"want.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table want
	 * @ibatorgenerated  Thu Apr 16 10:33:39 CST 2015
	 */
	private static class UpdateByExampleParms extends WantExample {
		private Object record;

		public UpdateByExampleParms(Object record, WantExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	/**
	 * 分页查询
	 * @author 浩然
	 * @param skipCount
	 * @param maxCount
	 * @param example
	 * @return
	 */
	public List<Want> selectByPage(int skipCount,int maxCount,WantExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"want.ibatorgenerated_selectByExample",example,skipCount,maxCount );
		return list;
	}
}